id: dc87c967-61d2-48e9-9fe1-26920944ca57
name: Cisco SE - Uncommon application behavior
description: |
  'Query searches for uncommon application behavior events.'
severity: Medium
requiredDataConnectors:
  - connectorId: CiscoSecureEndpoint
    dataTypes:
      - CiscoSecureEndpoint
tactics:
  - Execution
relevantTechniques:
  - T1204.002
query: |
  CiscoSecureEndpoint
  | where TimeGenerated > ago(24h)
  | where ThreatName has 'launched a shell'
  | order by TimeGenerated desc
  | extend HostCustomEntity = DstHostname
entityMappings:
  - entityType: Host
    fieldMappings:
      - identifier: HostName
        columnName: HostCustomEntity
