name: Splunk Stored XSS conf-web Settings on Premises
id: ed1209ef-228d-4dab-9856-be9369925a5c
version: 1
date: '2024-07-01'
author: Rod Soto, Chase Franklin
status: production
type: Hunting
data_source:
- Splunk
description: This hunting detection provides information on exploitation of stored XSS against /configs/conf-web/settings by an admin level user. 
search: '`splunk_python` *script* *eval* 
  | stats min(_time) as firstTime max(_time) as lastTime by index, sourcetype, host 
  | `security_content_ctime(firstTime)` 
  | `security_content_ctime(lastTime)` 
  | `splunk_stored_xss_conf_web_settings_on_premises_filter`'
how_to_implement: Requires access to internal indexes.
known_false_positives: This is a hunting search and will produce false positives, operator must identify XSS elemetns in the splunk_python log related to the vulnerable endpoint. 
references:
- https://advisory.splunk.com/advisories/SVD-2024-0717
cve:
- CVE-2024-36987
tags:
  analytic_story:
  - Splunk Vulnerabilities
  asset_type: Splunk Server
  cis20:
  - CIS 3
  - CIS 5
  - CIS 16
  confidence: 100
  impact: 20
  kill_chain_phases:
  - Exploitation
  message: Possible XSS attack against $host$
  mitre_attack_id:
  - T1189
  nist:
  - DE.CM
  observable:
  - name: host
    type: Hostname
    role:
    - Victim
  product:
  - Splunk Enterprise
  required_fields:
  - UPDATE
  risk_score: 20
  security_domain: endpoint
tests:
- name: True Positive Test
  attack_data:
  - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1189/splunk/SVD-2024-0717_python_log_splunk_python.log
    source: /opt/splunk/var/log/splunk/python.log
    sourcetype: splunk_python
    custom_index: _internal

