id: cc5780ce-3245-4bba-8bc1-e9048c2257ce
name: Changes to Application Ownership
description: |
  'Detects changes to the ownership of an appplicaiton.
    Monitor these changes to make sure that they were authorized.
    Ref: https://docs.microsoft.com/azure/active-directory/fundamentals/security-operations-applications#new-owner'
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActiveDirectory
    dataTypes:
      - AuditLogs
queryFrequency: 1d
queryPeriod: 1d
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Persistence
  - PrivilegeEscalation
relevantTechniques:
  - T1078.004
tags:
  - AADSecOpsGuide
query: |
  AuditLogs
    | where Category =~ "ApplicationManagement"
    | where OperationName =~ "Add owner to application"
    | extend appName = tostring(parse_json(tostring(InitiatedBy.app)).displayName)
    | extend UPN = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
    | extend UpdatedBy = iif(isnotempty(appName), appName, UPN)
    | extend mod_props = TargetResources[0].modifiedProperties
    | extend AddedUser = TargetResources[0].userPrincipalName
    | mv-expand mod_props
    | where mod_props.displayName =~ "Application.DisplayName"
    | extend AppName = tostring(parse_json(tostring(mod_props.newValue)))
    | project-reorder TimeGenerated, OperationName, AppName, AddedUser, UpdatedBy
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: UpdatedBy
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: AddedUser
version: 1.0.1
kind: Scheduled
metadata:
    source:
        kind: Community
    author:
        name: Pete Bryan
    support:
        tier: Community
    categories:
        domains: [ "Security - Others" ]