id: 1BDB9A37-DC72-4C5A-A222-08443865DC0D
name: Application not using client credentials
description: |
  'This query searches for application not using a client certificate or secret is not secure.'    
requiredDataConnectors:
  - connectorId: SenservaPro
    dataTypes:
      - SenservaPro_CL
tactics:
  - Impact
relevantTechniques:
  - T1529
  - T1485
query: |
  let timeframe = 14d;
  SenservaPro_CL
  | where TimeGenerated >= ago(timeframe)
  | where ControlName_s == 'ApplicationNotUsingClientCredentials'