id: cefd7f18-9359-4a99-bd18-965983bb724d
name: SlackAudit - Applications installed
description: |
  'This query searches for application installation events.'
severity: Medium
requiredDataConnectors:
  - connectorId: SlackAuditAPI
    dataTypes:
      - SlackAudit_CL
tactics:
  - InitialAccess
relevantTechniques:
  - T1133
query: |
  SlackAudit
  | where TimeGenerated > ago(24h)
  | where DvcAction =~ 'app_installed'
  | summarize by SrcUserName, EntityAppName
  | extend AccountCustomEntity = SrcUserName
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: AccountCustomEntity