name: Sync detection content
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: ./sync.sh
      - name: Commit updates
        run: |
          git config --global user.name 'SyncBot'
          git config --global user.email 'bot@optyx.io'
          git commit -am "Auto updated detection content" && git push || echo "No changes to commit"
