name: Sync detection content
on:
  schedule:
    - cron: "*/30 * * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          repository: d3vzer0/decon-content
          token: ${{ secrets.GIT_SECRET }}

      - name: Run a one-line script
        run: ./sync.sh
      - name: Commit updates
        run: |
          git config --global user.name 'GitHub Actions [Bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add --all
          git commit -m "Synced detection content" || echo "No changes to commit"
          git push
